# Marcelo Eduardo Redoschi - September 2026
# -----------------------------------------
FROM postgres:18.6-alpine3.24
COPY ../config/postgres-18_6-container-config.sql docker-entrypoint-initdb.d/
RUN apk add --no-cache nano
COPY --chown=postgres:postgres ../config/postgres-18_6-container-pgpass /var/lib/postgresql/.pgpass
RUN chmod 0600 /var/lib/postgresql/.pgpass
# Remove the cache https://stackoverflow.com/questions/49118579/alpine-dockerfile-advantages-of-no-cache-vs-rm-var-cache-apk#49119046
RUN rm -vrf /var/cache/apk/*
RUN /usr/local/bin/docker-entrypoint.sh
STOPSIGNAL SIGINT
EXPOSE 5432
CMD ["postgres"]